apps/core/urls.py
from django.urls import path, re_path

from .views import DashbordView, SampleDisplayView, SampleStatusView, SampleCsvView

urlpatterns = [
    path(
        r'',
        DashbordView.as_view(),
        name='dashboard'
    ),
    re_path(
        r'samples/(?P<slug>[\w-]+)/status/$',
        SampleStatusView.as_view(),
        name='sample_status_view'
    ),
    re_path(
        r'samples/(?P<slug>[\w-]+)/csv/$',
        SampleCsvView.as_view(),
        name='sample_csv_view'
    ),
    re_path(
        r'samples/(?P<slug>[\w-]+)/$',
        SampleDisplayView.as_view(),
        name='sample_display_view'
    ),
]

checkeramp/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from django.views.static import serve
from django.conf import settings


urlpatterns = [
    path('', include('apps.core.urls')),
    path('admin/', admin.site.urls),
]

urlpatterns += [
    re_path(r'^static/(?P<path>.*)$', serve, {
        'document_root': settings.STATIC_ROOT,
    }),
]

urlpatterns += [
    re_path(r'^media/(?P<path>.*)$', serve, {
        'document_root': settings.MEDIA_ROOT,
    }),
]

apps/core/models.py
import uuid
from django.db import models
from django.utils.text import slugify


class Sample(models.Model):
    TRESHOLD = 0.5

    sequence = models.TextField(
        'Sequence',
        blank=True
    )
    fasta_file = models.FileField(
        'Fasta',
        upload_to='fastas',
        blank=True
    )

    result = models.TextField(
        'Result',
        blank=True
    )

    uuid = models.UUIDField(
        default=uuid.uuid4,
        editable=False,
        db_index=True
    )

    slug = models.SlugField(
        unique=True,
        editable=False,
        max_length=150
    )

    created_date = models.DateTimeField(
        'Data created',
        auto_now_add=True
    )

    def _set_slug(self):
        self.slug = slugify(self.uuid, allow_unicode=True)

    def save(self, *args, **kwargs):
        if not self.pk:
            super(Sample, self).save(*args, **kwargs)

        self._set_slug()

        super(Sample, self).save()

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = 'sample'
        verbose_name_plural = 'samples'

        ordering = ['-created_date']

apps/core/forms.py
from io import StringIO

from django import forms
from django.forms import ModelForm
from django.core.files.base import ContentFile

from Bio import SeqIO

from .models import Sample


class SampleForm(ModelForm):
    sequence = forms.CharField(
        widget=forms.Textarea(attrs={"rows": 10, "cols": 100, "class": "form-control"}),
        required=False
    )

    def clean(self):
        cleaned_data = super(SampleForm, self).clean()

        sequence = cleaned_data.get('sequence')
        fasta_file = cleaned_data.get('fasta_file')

        if not sequence and not fasta_file:
            raise forms.ValidationError({
                'sequence': 'This field is required when FASTA is empty',
                'fasta_file': 'This field is required when sequence is empty'
            })

        if sequence and not list(SeqIO.parse(StringIO(sequence), "fasta")):
            raise forms.ValidationError({
                'sequence': 'Invalid sequence format',
            })

        return cleaned_data

    def save(self, commit=True):
        sample = super(SampleForm, self).save(commit=False)

        if commit:
            if sample.sequence:
                sample.fasta_file.save(
                    f'{sample.uuid}.fasta',
                    ContentFile(sample.sequence)
                )

            sample.save()

        return sample

    class Meta:
        model = Sample

        fields = '__all__'

apps/core/views.py
import json

from django.http import HttpResponse
from django.views.generic import View
from django.shortcuts import render, redirect
from django.contrib import messages
from django.views.decorators.csrf import csrf_exempt

from .forms import SampleForm
from .tasks import amp_predictor
from .models import Sample
from .utils import CSVGenerator


class DashbordView(View):
    template_name = 'index.html'

    def get(self, request):
        sample_form = SampleForm()

        context = {
            'sample_form': sample_form
        }

        return render(
            request,
            template_name=self.template_name,
            context=context
        )

    def post(self, request):
        sample_form = SampleForm(
            request.POST or None,
            request.FILES or None
        )

        if sample_form.is_valid():
            sample = sample_form.save()

            amp_predictor.delay(sample.pk)

            return redirect('sample_display_view', slug=sample.slug)
        else:
            messages.add_message(
                request,
                messages.ERROR,
                f'Processing failed. Check the details below.'
            )

        context = {
            'sample_form': sample_form
        }

        return render(
            request,
            template_name=self.template_name,
            context=context
        )


class SampleDisplayView(View):
    template_name = 'sample.html'

    def get(self, request, slug):
        sample = Sample.objects.get(slug=slug)

        if sample.result:
            result = json.loads(sample.result)
        else:
            result = []

        context = {
            'sample': sample,
            'result': result,
            'result_len': len(result)
        }

        return render(
            request,
            template_name=self.template_name,
            context=context
        )


class SampleCsvView(View):
    def get(self, request, slug):
        sample = Sample.objects.get(slug=slug)

        if sample.result:
            result = json.loads(sample.result)
        else:
            result = []

        csv = CSVGenerator(result=result)
        content = csv.to_csv()

        response = HttpResponse(content=content, content_type='application/csv')
        response['Content-Disposition'] = f'attachment; filename="{sample.slug}.csv"'

        return response


class SampleStatusView(View):
    def get(self, request, slug):
        sample = Sample.objects.get(slug=slug)

        if sample.result:
            return HttpResponse(content='DONE')
        else:
            return HttpResponse(content='IN_PROGRESS')

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" crossorigin="anonymous">

        {% block css %}{% endblock %}

        {% block title %}{% endblock %}
    </head>
    <body>
        {% block content %}{% endblock %}
        <script src="{% static 'js/jquery-3.4.1.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/popper.min.js' %}" crossorigin="anonymous"></script>
        <script src="{% static 'js/bootstrap.js' %}" crossorigin="anonymous"></script>
        {% block js %}{% endblock %}
    </body>
</html>

templates/footer.html
<footer class="center_box">
    <br><small>Version 1.0.0 powered by <strong>SLAVIC team</strong></small><br><br>
</footer>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    <title>CheckerAMP - dashboard</title>
{% endblock %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" crossorigin="anonymous">
{% endblock %}

{% block content %}
    <div class="jumbotron text-center">
        <h1>Welcome to CheckerAMP</h1>
        <p>Paste your sequences or upload multi-FASTA file</p>
    </div>

    <form role="form" method="post" action="{{ request.path }}" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="container p-4">
            <div class="row">
                {% for message in messages %}
                    <div class="col-sm-12">
                        <div class="alert alert-{{ message.tags }} alert-dismissable">
                            <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                            {{ message }}
                        </div>
                    </div>
                {% endfor %}

                <div class="col-sm-12">
                    <h3>Submit sequences for prediction</h3>
                    {{ sample_form.sequence }}
                    {% if sample_form.sequence.errors %}
                        <div class="text-danger">{{ sample_form.sequence.errors.as_text }}</div>
                    {% endif %}
                </div>
                <div class="col-sm-12 center_box">or</div>
                <div class="col-sm-12">
                    <div class="custom-file my-2">
                        <input type="file" class="custom-file-input" name="fasta_file" id="id_fasta_file">
                        <label class="custom-file-label" for="id_fasta_file">Choose FASTA file</label>
                    </div>
                    {% if sample_form.fasta_file.errors %}
                        <div class="text-danger">{{ sample_form.fasta_file.errors.as_text }}</div>
                    {% endif %}
                </div>
                <div class="col-sm-12">
                    <button type="submit" class="btn btn-primary">Start process</button>
                </div>
            </div>

            {% include 'footer.html' %}
        </div>
    </form>
{% endblock %}

{% block js %}
    <script>
        $(document).ready(function() {
            $('#id_fasta_file').on('change', function() {
                let fileName = $(this).val().split('\\').pop();
                $(this).next('.custom-file-label').addClass("selected").html(fileName);
            });
        })
    </script>
{% endblock %}

templates/sample.html
{% extends 'base.html' %}
{% load static %}

{% block css %}
    <link rel="stylesheet" href="{% static 'css/custom.css' %}" crossorigin="anonymous">
{% endblock %}

{% block title %}
    <title>CheckerAMP - {{ sample.uuid }}</title>
{% endblock %}

{% block content %}
    <div class="jumbotron text-center">
        <h1>Welcome to CheckerAMP</h1>
        <p>Back to <a href="{% url 'dashboard' %}">Upload view</a></p>
    </div>

    <div class="container">

        <div class="row">
            <div class="col-sm-6">
                <p>UUID: {{ sample.uuid }}</p>
                <p>Date created: {{ sample.created_date }}</p>
            </div>
            <div class="col-sm-6">
                <p>Fasta: <a href="{{ sample.fasta_file.url }}">Download</a></p>
            </div>
        </div>
        {% if sample.result %}
            <div class="row py-2">
                <div class="col-sm-6">
                    <p>Sequences amount: <span class="badge badge-dark">{{ result_len }}</span></p>
                </div>
                <div class="col-sm-6 right">
                    <a class="btn btn-dark text-white" href="{% url 'sample_csv_view' sample.slug %}">Download as
                        CSV</a>
                </div>
            </div>
            <div class="row">
                <div class="col-sm-12">
                    <table class="table table-hover table-striped table-sm">
                        <thead class="thead-dark">
                        <tr>
                            <th class="align-middle">ID</th>
                            <th class="align-middle">Sequence</th>
                            <th class="align-middle">Predicted class</th>
                            <th class="align-middle">AMP probability (%)</th>
                            <th class="align-middle">Target</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for sequence in result %}
                            <tr>
                                <td>{{ sequence.id }}</td>
                                <td class="long_seq">{{ sequence.data }}</td>
                                <td>
                                    {% if sequence.proba > 50 %}
                                        AMP
                                    {% else %}
                                        Non-AMP
                                    {% endif %}
                                </td>
                                <td>
                                    {% if sequence.proba >= 60 %}
                                        <span class="badge badge-success fixed_width">{{ sequence.proba }}</span>
                                    {% elif sequence.proba > 40 %}
                                        <span class="badge badge-warning fixed_width">{{ sequence.proba }}</span>
                                    {% else %}
                                        <span class="badge badge-danger fixed_width">{{ sequence.proba }}</span>
                                    {% endif %}
                                </td>
                                <td>
                                    {% if sequence.proba > 50 %}
                                        {% for model_name, prediction in sequence.additional_probabilities.items %}
                                            {% if prediction >= 80 %}
                                                <span class="badge badge-success cursor-pointer"
                                                      data-toggle="tooltip"
                                                      data-placement="top"
                                                      title="{{ prediction }}%">{{ model_name }}</span>
                                            {% elif prediction > 60 %}
                                                <span class="badge badge-warning cursor-pointer"
                                                      data-toggle="tooltip"
                                                      data-placement="top"
                                                      title="{{ prediction }}%">{{ model_name }}</span>
                                            {% endif %}
                                        {% endfor %}
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        {% else %}
            <div class="row">
                <div class="col-12 d-flex flex-row justify-content-center">
                    <div>
                        <img src="{% static "images/lg.dna-spin-spiral-preloader.gif" %}">
                    </div>
                </div>
            </div>
        {% endif %}

        {% include 'footer.html' %}
    </div>
{% endblock %}

{% block js %}
    {% if not sample.result %}
        <script type="text/javascript">
            setInterval(function () {
                $.ajax({
                    type: "GET",
                    url: "{% url 'sample_status_view' sample.uuid %}",
                })
                    .done(function (response) {
                        if (response === 'DONE') {
                            location.href = ("{% url 'sample_display_view' sample.uuid %}");
                        }
                    });
            }, 1000)
        </script>
    {% endif %}

    <script type="text/javascript">
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
{% endblock %}